(() => {
  const api = async (path, options={}) => {
    const res = await fetch('/api' + path, { credentials:'include', ...options, headers:{'Content-Type':'application/json', ...(options.headers||{})} });
    const data = await res.json().catch(()=>({}));
    if(!res.ok) throw new Error(data.error||'Erro de comunicação.');
    return data;
  };
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
  let me=null, pendingEmail='';

  function toast(m){window.showToast?.(m)}
  function appLocked(v){document.querySelector('.app')?.classList.toggle('authLocked',v);const g=$('#authGate');if(g)g.style.display=v?'grid':'none'}
  function publicShow(v){const p=$('#publicFirst');if(p)p.style.display=v?'block':'none'}
  function setRoleVisibility(role){
    $$('.navItem[data-page^="client-"]').forEach(x=>x.style.display=role==='client'?'flex':'none');
    $$('.navItem[data-page^="admin-"]').forEach(x=>x.style.display=role==='admin'?'flex':'none');
    $$('.role').forEach((x,i)=>x.style.display=(role==='client'&&i===0)||(role==='admin'&&i===1)?'block':'none');
    let out=$('#logoutNav'); if(!out){out=document.createElement('button');out.id='logoutNav';out.className='navItem logoutNav';out.innerHTML='<span class="navIcon">↪</span>Sair';out.onclick=logout;$('#sidebar')?.appendChild(out)}
  }
  async function who(){try{const d=await api('/me');me=d;return d}catch{me=null;return null}}
  async function logout(){await api('/auth/logout',{method:'POST'}).catch(()=>{});me=null;appLocked(true);publicShow(true);window.setAuthMode?.('login');toast('Sessão encerrada.');}

  function showVerification(email){pendingEmail=email;const form=$('#authForm'),box=$('#verifyBox');if(form)form.style.display='none';if(box){box.classList.add('show');$('#verifyText').textContent=`Enviámos um código de 6 dígitos para ${email}. Introduza-o para ativar a conta.`;$('#verifyStatus').textContent='O código é válido durante 10 minutos.';$('#verifyDemo').textContent='O código não é apresentado no site. Consulte o seu e-mail.';$('#verifyDemo').classList.add('show');$('#verify1')?.focus()}}
  function authModalClose(){window.closePublicAuth?.()}
  async function handleAuth(e){
    e.preventDefault();const mode=window.authMode||'login',email=$('#authEmail')?.value.trim(),password=$('#authPassword')?.value||'',err=$('#authError');if(err)err.textContent='';
    try{
      if(mode==='signup'){
        const confirm=$('#authPasswordConfirm')?.value||'',name=$('#authName')?.value.trim()||'Cliente BENGA';
        if(password!==confirm)throw new Error('As palavras-passe não coincidem.');
        const r=await api('/auth/register/request',{method:'POST',body:JSON.stringify({email,name,password})});showVerification(r.email);return;
      }
      const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});
      me={role:r.role,name:r.name,email:r.email};appLocked(false);publicShow(false);setRoleVisibility(r.role);window.showWelcome?.(r.role,r.name,()=>window.showPage(r.role==='admin'?'admin-dashboard':'client-home'));refresh();
    }catch(ex){if(err)err.textContent=ex.message;else toast(ex.message)}
  }
  async function confirmEmailCode(){const code=[1,2,3,4,5,6].map(i=>$('#verify'+i)?.value||'').join('');try{const r=await api('/auth/register/verify',{method:'POST',body:JSON.stringify({email:pendingEmail||$('#authEmail')?.value.trim(),code})});$('#verifyStatus').textContent='E-mail verificado. Conta criada com sucesso.';$('#verifyStatus').className='verifyStatus verifySuccess';me={role:r.role,name:r.name,email:r.email};setTimeout(()=>{appLocked(false);publicShow(false);setRoleVisibility('client');window.showPage('client-home');refresh()},500)}catch(ex){$('#verifyStatus').textContent=ex.message;$('#verifyStatus').className='verifyStatus verifyError'}}
  async function resendEmailCode(){try{await api('/auth/register/resend',{method:'POST',body:JSON.stringify({email:pendingEmail||$('#authEmail')?.value.trim()})});$('#verifyStatus').textContent='Novo código enviado. Verifique o seu e-mail.'}catch(ex){$('#verifyStatus').textContent=ex.message}}
  function socialAuth(provider){
    const p=provider.toLowerCase(); fetch('/api/auth/'+p+'/start').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Login social não configurado.');location.href=d.redirect}).catch(ex=>toast(ex.message));
  }

  async function publicData(){try{const d=await api('/public');const pf=$('#publicFirst');if(!pf)return;const order=pf.querySelector('[data-orders]');if(order){order.dataset.counter=String(d.stat_envios||0);order.textContent='0'}const rev=pf.querySelector('[data-counter="1284"]');if(rev){rev.dataset.counter=String(d.review_count||0);rev.textContent='0'}const proof=pf.querySelector('.pf-proof b');if(proof)proof.textContent=`${d.review_count||0} avaliações verificadas`;const reviewTitle=pf.querySelector('.pf-rating h3');if(reviewTitle)reviewTitle.textContent=`${d.review_count||0} avaliações verificadas`;const avg=pf.querySelector('.pf-big');if(avg)avg.textContent=d.review_average?String(d.review_average).replace('.',','):'—';}catch(_){}}


  async function clientData(){if(me?.role!=='client')return;try{const orders=await api('/orders'),notes=await api('/notifications'),addresses=await api('/addresses'),pay=await api('/payment-info'),review=await api('/reviews/mine');renderClientHome(orders,notes);renderClientOrders(orders);renderNotes(notes);renderAddresses(addresses);renderPayments(pay);renderReview(review,orders);return {orders,notes,addresses,pay,review};}catch(ex){toast(ex.message)}}
  function renderClientHome(orders,notes){
    const a=$$('#client-home .animatedStats .aStatNum'),tr=orders.filter(o=>o.status==='Em trânsito').length,pp=orders.filter(o=>o.payment_status!=='Pago').length,n=notes.filter(x=>!x.read).length;
    [orders.length,tr,pp,n].forEach((v,i)=>{if(a[i])a[i].textContent=String(v).padStart(2,'0')});
    const focus=$('#client-home .focusCard');
    if(!focus)return;
    const o=orders[0];
    if(o){
      focus.innerHTML=`<div class="sideTitle"><h3>Encomenda em destaque</h3><span class="status info">${esc(o.status)}</span></div><div class="bigNumber">${esc(o.tracking_code||'—')}</div><p>${esc(o.origin||'')} → ${esc(o.destination||'')} · ${esc(o.model||o.type||'')} · ${o.quantity||1} un.</p><button class="btn ghost" onclick="document.getElementById('trackCode').value='${esc(o.tracking_code||'')}';showPage('client-track')" style="margin-top:13px">Ver percurso →</button>`;
    }else{
      focus.innerHTML=`<div class="sideTitle"><h3>Encomenda em destaque</h3><span class="status pending">Sem pedidos</span></div><div class="bigNumber">—</div><p>Ainda não existem encomendas nesta conta.</p><button class="btn primary" onclick="showPage('client-new')" style="margin-top:13px">Criar primeira encomenda →</button>`;
    }
  }

  function renderClientOrders(rows){const p=$('#client-orders');if(!p)return;const nums=p.querySelectorAll('.grid4 .bigNum'),tr=rows.filter(o=>o.status==='Em trânsito').length,de=rows.filter(o=>o.status==='Entregue').length,pend=rows.filter(o=>o.payment_status!=='Pago').length;[rows.length,tr,de,pend].forEach((v,i)=>{if(nums[i])nums[i].textContent=String(v)});const tb=p.querySelector('table tbody');if(tb)tb.innerHTML=rows.length?rows.map(o=>`<tr><td><strong>${esc(o.tracking_code||'—')}</strong></td><td>${esc(o.created_at||'')}</td><td>${esc(o.origin)} → ${esc(o.destination)}</td><td>${esc(o.model||o.type)} · ${o.quantity} un.</td><td>${money(o.total_eur)}</td><td><span class="status info">${esc(o.status)}</span></td><td><button class="linkBtn" onclick="document.getElementById('trackCode').value='${esc(o.tracking_code||'')}';showPage('client-track')">Rastrear</button></td></tr>`).join(''):'<tr><td colspan="7"><div class="emptyInline">Ainda não tem encomendas.</div></td></tr>'}
  function renderNotes(rows){const p=$('#client-notifs');if(!p)return;const list=p.querySelector('.notifList');if(!list)return;list.innerHTML=rows.length?rows.map(n=>`<div class="notifItem ${n.read?'':'new'}"><span class="notifIcon">●</span><div><strong>Atualização BENGA</strong><p>${esc(n.text)}</p><small>${esc(n.created_at)}</small></div></div>`).join(''):'<div class="emptyInline">Sem notificações.</div>'}
  function renderAddresses(rows){const p=$('#client-addresses');if(!p)return;let holder=p.querySelector('.clientAddressList');if(!holder){holder=document.createElement('div');holder.className='clientAddressList';p.appendChild(holder)}holder.innerHTML=rows.length?rows.map(a=>`<div class="card"><span class="status ${a.is_main?'ok':'info'}">${a.is_main?'Principal':'Guardada'}</span><h3>${esc(a.name)}</h3><p>${esc(a.address)}</p><small>${esc(a.province||'')} · ${esc(a.municipality||'')}</small></div>`).join(''):'<div class="emptyInline">Nenhuma morada pessoal guardada.</div>'}
  function renderPayments(p){
    const page=$('#client-payments');if(!page)return;
    const lines=page.querySelectorAll('.line b');
    if(lines[0])lines[0].textContent=p.nib||'';
    if(lines[1])lines[1].textContent=p.iban||'';
    const ps=page.querySelectorAll('.card p');
    if(ps[0])ps[0].innerHTML='Método disponível: <b>'+esc(p.ao_method||'Multicaixa Express')+'</b>';
    if(ps[1])ps[1].innerHTML='Métodos disponíveis: <b>'+esc(p.pt_method||'MB WAY / Transferência')+'</b>';
    const holder=page.querySelector('.card[style] p b');
    if(holder)holder.textContent=p.holder||'Rachid Gomes';
    const instr=page.querySelector('.paymentInstruction');
    if(instr)instr.textContent=p.pay_info||'';
    const wa=page.querySelector('.btn.primary');
    if(wa){
      const num=String(p.whatsapp||'').replace(/\D/g,'');
      const code=p.tracking_code||'';
      const msg=encodeURIComponent('Olá BENGA ENVIOS! Já efetuei o pagamento da encomenda '+code+'. Valor: '+(p.amount!=null?Number(p.amount).toFixed(2):'')+' €. Vou enviar o comprovativo para confirmação.');
      wa.textContent='Enviar comprovativo pelo WhatsApp';
      wa.onclick=()=>{ if(num) window.open('https://wa.me/'+num+'?text='+msg,'_blank','noopener,noreferrer'); else toast('WhatsApp de apoio não configurado.'); };
    }
  }

  function renderReview(r,orders){const page=$('#client-review');if(!page)return;const hero=page.querySelector('.reviewHero h2');if(hero)hero.textContent=r?`Avaliação enviada · ${r.stars}★`:'Avaliar a BENGA';const card=page.querySelector('.twoCol .card');if(card&&!r&&!orders.some(o=>o.status==='Entregue'))card.innerHTML='<span class="status info">Ainda não disponível</span><h3>Sem encomenda entregue</h3><p>Depois de uma entrega concluída poderá enviar a sua avaliação.</p>';if(card&&r){card.innerHTML=`<span class="status ok">Avaliação recebida</span><h3>${r.stars} estrelas</h3><p>${esc(r.text)}</p>`}}

  async function createOrder(){
    const type=$('#calcType')?.value;if(type==='other'){toast('Para outra mercadoria, contacte o suporte para obter uma cotação.');return}
    try{const body={type,purchase_value:(type==='computer'||type==='android')?Number($('#purchaseValue')?.value||0):undefined,model:(type==='iphone'||type==='playstation')?$('#modelSelect')?.value:undefined,quantity:Number($('#calcQty')?.value||1),origin:$('#orderOrigin')?.value||'Angola',destination:$('#orderDestination')?.value||'Portugal'};const r=await api('/orders',{method:'POST',body:JSON.stringify(body)});$('#generatedCode').textContent=r.code||'Gerado';toast(`Encomenda ${r.code} criada. Total: ${money(r.total)}.`);await clientData();window.showPage('client-orders')}catch(ex){toast(ex.message)}}
  async function track(){const code=($('#trackCode')?.value||'').trim().toUpperCase();if(!code){toast('Introduza o código.');return}try{const r=await fetch('/api/track/'+encodeURIComponent(code));const d=await r.json();if(!r.ok)throw new Error(d.error||'Não encontrado.');$('#trackResult').style.display='grid';$('#trackResultCode').textContent=d.code;$('#trackResult').querySelector('p').textContent=`Estado: ${d.status} · ${d.origin} → ${d.destination} · ${d.location||''}`;}catch(ex){$('#trackResult').style.display='grid';$('#trackResultCode').textContent='Não encontrado';$('#trackResult').querySelector('p').textContent=ex.message}}
  async function submitReview(){try{const stars=Number(window.reviewStars||5),text=$('#reviewText')?.value||'';await api('/reviews',{method:'POST',body:JSON.stringify({stars,text})});toast('Avaliação enviada.');await clientData()}catch(ex){toast(ex.message)}}

  async function adminData(){if(me?.role!=='admin')return;try{const st=await api('/admin/stats'),orders=await api('/admin/orders'),clients=await api('/admin/clients'),reviews=await api('/admin/reviews'),support=await api('/admin/support'),settings=await api('/admin/settings'),audit=await api('/admin/audit');renderAdmin(st,orders,clients,reviews,support);window.__adminSettings=settings;renderAdminSettings(settings);renderAdminAudit(audit)}catch(ex){toast(ex.message)}}
  function renderAdmin(st,orders,clients,reviews,support){const nums=$$('#admin-dashboard .adminKpis .statCard strong');[st.clients,st.total,st.transit,orders.filter(o=>o.payment_status!=='Pago').length].forEach((v,i)=>{if(nums[i])nums[i].textContent=String(v)});const orb=$('#admin-dashboard .adminHeroOrb strong');if(orb)orb.textContent=String(st.total);const mega=$$('#admin-dashboard .adminImageStrip .megaValue');if(mega[0])mega[0].textContent=money(st.revenue);if(mega[1])mega[1].textContent=String(st.reviews);const list=$('#admin-dashboard .compactList');if(list)list.innerHTML=orders.length?orders.slice(0,8).map(o=>`<div><span class="avatar">${esc((o.name||'CL').slice(0,2).toUpperCase())}</span><div><strong>${esc(o.tracking_code||'—')}</strong><small>${esc(o.name||'Cliente')} · ${esc(o.origin)} → ${esc(o.destination)} · ${esc(o.model||o.type)}</small></div><span class="status info">${esc(o.status)}</span></div>`).join(''):'<div class="emptyInline">Sem encomendas.</div>';const pay=$('#admin-dashboard .paymentRows');if(pay)pay.innerHTML=orders.filter(o=>o.payment_status!=='Pago').slice(0,5).map(o=>`<div><span>${esc(o.tracking_code||'#')}</span><strong>${money(o.total_eur)}</strong><em class="pending">${esc(o.payment_status)}</em></div>`).join('')||'<div class="emptyInline">Sem pagamentos pendentes.</div>';renderOrdersAdmin(orders);renderClientsAdmin(clients);renderReviewsAdmin(reviews);renderSupportAdmin(support)}
  function renderOrdersAdmin(rows){const tb=$('#admin-orders table tbody');if(!tb)return;tb.innerHTML=rows.length?rows.map(o=>`<tr><td><strong>${esc(o.tracking_code||'—')}</strong></td><td>${esc(o.name||'Cliente')}</td><td>${esc(o.origin)} → ${esc(o.destination)}</td><td>${esc(o.model||o.type)} · ${o.quantity||1} un.</td><td>${money(o.total_eur)}</td><td><span class="status ${o.payment_status==='Pago'?'ok':'pending'}">${esc(o.payment_status)}</span></td><td><span class="status info">${esc(o.status)}</span></td><td><button class="linkBtn" onclick="openProdOrderEditor(${o.id},${Number(o.total_eur)||0},'${esc(o.status)}','${esc(o.location||'')}','${esc(o.payment_status||'Pendente')}')">Editar</button></td></tr>`).join(''):'<tr><td colspan="8"><div class="emptyInline">Sem encomendas registadas.</div></td></tr>'}
  function renderClientsAdmin(rows){const tb=$('#admin-clients table tbody');if(!tb)return;tb.innerHTML=rows.length?rows.map(c=>`<tr><td><strong>${esc(c.name)}</strong><br><small>${esc(c.email)}</small></td><td>${esc(c.phone||'—')}</td><td>${c.orders}</td><td>${esc(c.provider||'password')}</td><td>${esc(c.created_at)}</td><td><span class="status ok">Ativo</span></td></tr>`).join(''):'<tr><td colspan="6"><div class="emptyInline">Ainda não existem clientes.</div></td></tr>'}
  function renderReviewsAdmin(rows){const p=$('#admin-reviews');if(!p)return;const nums=p.querySelectorAll('.bigNum'),published=rows.filter(r=>r.status==='Publicada').length,pending=rows.filter(r=>r.status!=='Publicada').length,avg=rows.length?rows.reduce((a,r)=>a+Number(r.stars||0),0)/rows.length:0;[rows.length,published,pending,avg?avg.toFixed(1)+' ★':'—'].forEach((v,i)=>{if(nums[i])nums[i].textContent=v});const tb=p.querySelector('table tbody');if(tb)tb.innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.route||'—')}</td><td>${'★'.repeat(r.stars||0)}</td><td>${esc(r.text)}</td><td>${esc(r.created_at)}</td><td><span class="status ${r.status==='Publicada'?'ok':'pending'}">${esc(r.status)}</span></td><td><button class="linkBtn" onclick="moderateProdReview(${r.id},'${r.status==='Publicada'?'Oculta':'Publicada'}')">${r.status==='Publicada'?'Ocultar':'Publicar'}</button></td></tr>`).join(''):'<tr><td colspan="7"><div class="emptyInline">Nenhuma avaliação recebida.</div></td></tr>'}
  function renderSupportAdmin(rows){const list=$('#admin-support .ticketList');if(!list)return;list.querySelectorAll('.ticket').forEach(x=>x.remove());if(rows.length)rows.slice(0,10).forEach(t=>{const d=document.createElement('div');d.className='ticket';d.innerHTML=`<div class="avatar">${esc((t.name||'CL').slice(0,2).toUpperCase())}</div><div><strong>${esc(t.subject)}</strong><small>${esc(t.message).slice(0,90)}</small></div><span>${esc(t.created_at)}</span>`;list.appendChild(d)});else list.insertAdjacentHTML('beforeend','<div class="emptyInline">Sem mensagens de suporte.</div>')}
  function renderAdminSettings(s){if(!s)return;const adminAoAddress=$('#adminAoAddress'),adminPtAddress=$('#adminPtAddress');if(adminAoAddress)adminAoAddress.value=s.addr_ao||'';if(adminPtAddress)adminPtAddress.value=s.addr_pt||'';if($('#payNib'))$('#payNib').value=s.pay_nib||'';if($('#payIban'))$('#payIban').value=s.pay_iban||'';if($('#payHolder'))$('#payHolder').value=s.pay_holder||'';if($('#payAoMethod'))$('#payAoMethod').value=s.pay_ao_method||'Multicaixa Express';if($('#payPtMethod'))$('#payPtMethod').value=s.pay_pt_method||'MB WAY / Transferência';if($('#payWa1'))$('#payWa1').value=s.whatsapp||'';if($('#payWa2'))$('#payWa2').value=s.whatsapp2||'';if($('#payInstagram'))$('#payInstagram').value=s.instagram||'';renderProductionPricing(s.pricing)}
  function renderProductionPricing(p){if(!p)return;const pc=$('#pcEditor');if(pc)pc.innerHTML=p.computer.map((r,i)=>`<div class="rateEditorRow"><label>${i===p.computer.length-1?'Superior a 900 €':`${Number(r[0]).toFixed(2).replace('.',',')} € – ${Number(r[1]).toFixed(2).replace('.',',')} €`}<input data-prodpcmin="${i}" value="${r[0]}" type="number" step="0.01"></label><label>Máximo<input data-prodpcmax="${i}" value="${r[1]}" type="number" step="0.01"></label><label>Envio (€)<input data-prodpcRate="${i}" value="${r[2]}" type="number" step="0.01"></label></div>`).join('');const an=$('#androidEditor');if(an)an.innerHTML=p.android.map((r,i)=>`<div class="rateEditorRow"><label>${i===p.android.length-1?'Superior a 900 €':`${Number(r[0]).toFixed(2).replace('.',',')} € – ${Number(r[1]).toFixed(2).replace('.',',')} €`}<input data-prodanmin="${i}" value="${r[0]}" type="number" step="0.01"></label><label>Máximo<input data-prodanmax="${i}" value="${r[1]}" type="number" step="0.01"></label><label>Envio (€)<input data-prodanRate="${i}" value="${r[2]}" type="number" step="0.01"></label></div>`).join('');const ip=$('#iphoneEditor');if(ip)ip.innerHTML=p.iphone.map((r,i)=>`<div class="rateEditorRow"><label style="grid-column:1 / 3">${esc(r[0])}</label><label>Envio (€)<input data-prodip="${i}" value="${r[1]}" type="number" step="0.01"></label></div>`).join('');const ps=$('#psEditor');if(ps)ps.innerHTML=p.playstation.map((r,i)=>`<div class="rateEditorRow"><label style="grid-column:1 / 3">${esc(r[0])}</label><label>Envio (€)<input data-prodp="${i}" value="${r[1]}" type="number" step="0.01"></label></div>`).join('')}
  async function saveProdPricing(){try{const s=window.__adminSettings||await api('/admin/settings'),p=structuredClone(s.pricing);$$('[data-prodpcmin]').forEach(e=>{const i=+e.dataset.prodpcmin;p.computer[i]=[+e.value,+$(`[data-prodpcmax="${i}"]`).value,+$(`[data-prodpcRate="${i}"]`).value]});$$('[data-prodanmin]').forEach(e=>{const i=+e.dataset.prodanmin;p.android[i]=[+e.value,+$(`[data-prodanmax="${i}"]`).value,+$(`[data-prodanRate="${i}"]`).value]});$$('[data-prodip]').forEach(e=>p.iphone[+e.dataset.prodip][1]=+e.value);$$('[data-prodp]').forEach(e=>p.playstation[+e.dataset.prodp][1]=+e.value);p.computerDays=$('#cfgPcDays')?.value||p.computerDays;p.androidDays=$('#cfgAndroidDays')?.value||p.androidDays;p.playstationDays=$('#cfgPsDays')?.value||p.playstationDays;p.customsIncluded=($('#cfgCustoms')?.value||'sim')==='sim';p.packagingIncluded=($('#cfgPackaging')?.value||'sim')==='sim';p.currency=$('#cfgCurrency')?.value||p.currency;await api('/admin/settings',{method:'PUT',body:JSON.stringify({pricing:p})});toast('Preços guardados.');await adminData()}catch(ex){toast(ex.message)}}
  async function saveProdPayment(){try{const holder=$('#payHolder')?.value?.trim()||'Rachid Gomes',nib=$('#payNib')?.value?.trim()||'',aoMethod=$('#payAoMethod')?.value?.trim()||'Multicaixa Express',iban=$('#payIban')?.value?.trim()||'',ptMethod=$('#payPtMethod')?.value?.trim()||'MB WAY / Transferência';if(!nib||!iban)throw new Error('Preencha o NIB e o IBAN.');const info='Titular: '+holder+'\nAngola NIB: '+nib+' ('+aoMethod+')\nPortugal IBAN: '+iban+' ('+ptMethod+')\nUse o número da encomenda como referência e envie o comprovativo pelo WhatsApp. Aguarde a confirmação antes de avançar.';await api('/admin/settings',{method:'PUT',body:JSON.stringify({pay_holder:holder,pay_nib:nib,pay_ao_method:aoMethod,pay_iban:iban,pay_pt_method:ptMethod,whatsapp:$('#payWa1')?.value,whatsapp2:$('#payWa2')?.value,instagram:$('#payInstagram')?.value,pay_info:info,pay_methods:'Transferência bancária — sem pagamento online'})});toast('Dados de pagamento guardados.');await adminData()}catch(ex){toast(ex.message)}}
  async function saveProdAddr(){try{await api('/admin/settings',{method:'PUT',body:JSON.stringify({addr_ao:$('#adminAoAddress')?.value,addr_pt:$('#adminPtAddress')?.value})});toast('Moradas guardadas.');await adminData()}catch(ex){toast(ex.message)}}
  async function prodEditOrder(id,total,status,location,payment){const body={total_eur:Number($('#editOrderPrice')?.value||total),status:$('#editOrderStatus')?.value||status,location:$('#editOrderLocation')?.value||location,payment_status:$('#editOrderPayment')?.value||payment};try{await api('/admin/orders/'+id,{method:'PUT',body:JSON.stringify(body)});window.closeOrderEditor?.();toast('Encomenda atualizada.');await adminData()}catch(ex){toast(ex.message)}}
  async function moderateProdReview(id,status){try{await api('/admin/reviews/'+id+'/status',{method:'POST',body:JSON.stringify({status})});await adminData()}catch(ex){toast(ex.message)}}
  function openProdOrderEditor(id,total,status,location,payment){const modal=$('#orderEditModal');if(!modal)return;$('#editOrderCode').value=id;$('#editOrderPrice').value=total;$('#editOrderStatus').value=status;$('#editOrderLocation').value=location;let s=$('#editOrderPayment');if(!s){s=document.createElement('select');s.id='editOrderPayment';s.innerHTML='<option>Pendente</option><option>Comprovativo enviado</option><option>Em análise</option><option>Pago</option><option>Cancelado</option>';$('#editOrderLocation').parentElement.appendChild(s)}s.value=payment;modal.classList.add('show');window.saveEditedOrder=()=>prodEditOrder(id,total,status,location,payment)}

  const oldShow=window.showPage;window.showPage=async function(id){oldShow?.(id);try{if(id.startsWith('client-'))await clientData();if(id.startsWith('admin-'))await adminData()}catch(ex){toast(ex.message)}};
  window.handleAuth=handleAuth;window.confirmEmailCode=confirmEmailCode;window.resendEmailCode=resendEmailCode;window.socialAuth=socialAuth;window.logoutSession=logout;window.generateOrderAndSubmit=createOrder;window.submitReview=submitReview;window.trackDemo=track;window.savePricing=saveProdPricing;window.savePaymentSettings=saveProdPayment;window.saveBengaAddresses=saveProdAddr;window.openProdOrderEditor=openProdOrderEditor;window.moderateProdReview=moderateProdReview;
  window.adminCreateOrder=()=>toast('A criação de encomendas é iniciada pelo cliente; o administrador pode editar qualquer pedido existente.');
  window.generateOrderCode=()=>toast('O código de rastreio é gerado automaticamente ao criar a encomenda.');
  window.setAuthMode=window.setAuthMode||function(){};
  window.addEventListener('load',async()=>{await publicData();const x=await who();if(x){appLocked(false);publicShow(false);setRoleVisibility(x.role);refresh()}else{appLocked(false);publicShow(true)}});
  async function refresh(){if(me?.role==='client')await clientData();if(me?.role==='admin')await adminData();}
})();
